-- Data simulasi; akun sengaja terkunci. Jalankan php scripts/activate-demo.php setelah impor.
SET NAMES utf8mb4;
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('1','Administrator akademik','admin@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:46','2026-10-07 13:37:46','admin');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('2','Akhyar','mahasiswa@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:46','2026-10-07 13:37:46','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('3','Nadia Rahma','mhs02@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:46','2026-10-07 13:37:46','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('4','Farhan Putra','mhs03@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:47','2026-10-07 13:37:47','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('5','Bella Nabila','mhs04@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:47','2026-10-07 13:37:47','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('6','Rizky Fadli','mhs05@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:47','2026-10-07 13:37:47','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('7','Salsabila Putri','mhs06@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:47','2026-10-07 13:37:47','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('8','Dimas Pratama','mhs07@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:48','2026-10-07 13:37:48','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('9','Aulia Fitri','mhs08@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:48','2026-10-07 13:37:48','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('10','Fauzan Arif','mhs09@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:48','2026-10-07 13:37:48','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('11','Nisa Hanifah','mhs10@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:48','2026-10-07 13:37:48','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('12','Raka Wijaya','mhs11@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:49','2026-10-07 13:37:49','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('13','Intan Safira','mhs12@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:49','2026-10-07 13:37:49','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('14','Yoga Pratama','mhs13@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:49','2026-10-07 13:37:49','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('15','Siti Zahra','mhs14@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:49','2026-10-07 13:37:49','mahasiswa');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('16','Dr. Ahmad Fadhli','dosen@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:50','2026-10-07 13:37:50','dosen');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('17','Dr. Siti Marlina','dosen2@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:50','2026-10-07 13:37:50','dosen');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('18','Dr. Teuku Zulkifli','dosen3@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:50','2026-10-07 13:37:50','dosen');
INSERT INTO `users` (`id`,`name`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`role`) VALUES ('19','Dr. Dewi Anggraini','dosen4@demo.test',NULL,'!akun-demo-perlu-diaktifkan!',NULL,'2026-10-07 13:37:51','2026-10-07 13:37:51','dosen');
INSERT INTO `fakultas` (`id`,`kode`,`nama`) VALUES ('1','FMIPA','Fakultas Matematika dan Ilmu Pengetahuan Alam');
INSERT INTO `fakultas` (`id`,`kode`,`nama`) VALUES ('2','FT','Fakultas Teknik');
INSERT INTO `prodi` (`id`,`fakultas_id`,`kode`,`nama`,`batas_sks`) VALUES ('1','1','MKIA','Magister Kecerdasan Artifisial','24');
INSERT INTO `prodi` (`id`,`fakultas_id`,`kode`,`nama`,`batas_sks`) VALUES ('2','2','INFO','Informatika','24');
INSERT INTO `prodi` (`id`,`fakultas_id`,`kode`,`nama`,`batas_sks`) VALUES ('3','1','MATH','Matematika','24');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('1','2','1','260820701100010','Akhyar','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('2','3','1','SIM202600002','Nadia Rahma','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('3','4','1','SIM202600003','Farhan Putra','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('4','5','1','SIM202600004','Bella Nabila','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('5','6','1','SIM202600005','Rizky Fadli','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('6','7','1','SIM202600006','Salsabila Putri','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('7','8','1','SIM202600007','Dimas Pratama','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('8','9','1','SIM202600008','Aulia Fitri','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('9','10','1','SIM202600009','Fauzan Arif','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('10','11','1','SIM202600010','Nisa Hanifah','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('11','12','1','SIM202600011','Raka Wijaya','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('12','13','1','SIM202600012','Intan Safira','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('13','14','2','SIM202600013','Yoga Pratama','2026');
INSERT INTO `mahasiswa` (`id`,`user_id`,`prodi_id`,`npm`,`nama`,`angkatan`) VALUES ('14','15','3','SIM202600014','Siti Zahra','2026');
INSERT INTO `dosen` (`id`,`user_id`,`prodi_id`,`kode`,`nama`) VALUES ('1','16','1','DSN001','Dr. Ahmad Fadhli');
INSERT INTO `dosen` (`id`,`user_id`,`prodi_id`,`kode`,`nama`) VALUES ('2','17','1','DSN002','Dr. Siti Marlina');
INSERT INTO `dosen` (`id`,`user_id`,`prodi_id`,`kode`,`nama`) VALUES ('3','18','1','DSN003','Dr. Teuku Zulkifli');
INSERT INTO `dosen` (`id`,`user_id`,`prodi_id`,`kode`,`nama`) VALUES ('4','19','1','DSN004','Dr. Dewi Anggraini');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('1','1','MPD301','Manajemen dan Pemodelan Data','3');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('2','1','MPE302','Metode Penelitian','2');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('3','1','AIK303','Kecerdasan Artifisial','3');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('4','1','PSD304','Pemrograman untuk Sains Data','3');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('5','1','STA305','Statistika Lanjutan','3');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('6','1','BDA306','Big Data dan Analitika','3');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('7','1','ETK307','Etika Kecerdasan Artifisial','2');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('8','2','INF101','Algoritma dan Pemrograman','3');
INSERT INTO `matakuliah` (`id`,`prodi_id`,`kode`,`nama`,`sks`) VALUES ('9','1','PDB308','Praktikum Basis Data','2');
INSERT INTO `periode` (`id`,`nama`,`tahun_mulai`,`semester`,`krs_mulai`,`krs_selesai`,`aktif`) VALUES ('1','2025/2026 Genap','2025','Genap','2026-01-01','2026-02-15','0');
INSERT INTO `periode` (`id`,`nama`,`tahun_mulai`,`semester`,`krs_mulai`,`krs_selesai`,`aktif`) VALUES ('2','2026/2027 Ganjil','2026','Ganjil','2026-09-30','2026-10-21','1');
INSERT INTO `ruang` (`id`,`kode`,`nama`,`kapasitas`) VALUES ('1','B0101','Ruang B.01.01','30');
INSERT INTO `ruang` (`id`,`kode`,`nama`,`kapasitas`) VALUES ('2','LAB01','Laboratorium komputasi','24');
INSERT INTO `ruang` (`id`,`kode`,`nama`,`kapasitas`) VALUES ('3','B0102','Ruang B.01.02','30');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('1','1','2','1','A','12','2026-10-07 13:38:26','2026-10-07 13:38:26');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('2','2','2','2','A','12','2026-10-07 13:38:26','2026-10-07 13:38:26');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('3','3','2','3','A','12','2026-10-07 13:38:26','2026-10-07 13:38:26');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('4','4','2','1','A','12',NULL,NULL);
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('5','5','2','2','A','12',NULL,NULL);
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('6','6','2','3','A','12',NULL,NULL);
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('7','7','2','4','A','12',NULL,NULL);
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('8','1','2','1','B','3','2026-10-07 15:39:55','2026-10-07 15:38:13');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('9','1','1','1','A','12','2026-10-07 13:38:26','2026-10-07 13:38:26');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('10','3','1','3','A','12','2026-10-07 13:38:26','2026-10-07 13:38:26');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('11','4','1','2','A','12','2026-10-07 13:38:26','2026-10-07 13:38:26');
INSERT INTO `kelas` (`id`,`matakuliah_id`,`periode_id`,`dosen_id`,`kode`,`kapasitas`,`published_at`,`first_published_at`) VALUES ('12','9','2','1','A','12','2026-10-07 13:38:34','2026-10-07 13:38:34');
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('1','1','1','1','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('2','2','1','2','09:00:00','10:40:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('3','3','1','3','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('4','4','2','4','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('5','5','1','5','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('6','6','3','1','13:00:00','15:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('7','7','3','2','13:00:00','14:40:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('8','8','1','4','13:00:00','15:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('9','9','1','1','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('10','10','1','3','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('11','11','2','4','09:00:00','11:30:00','Luring',NULL);
INSERT INTO `jadwal` (`id`,`kelas_id`,`ruang_id`,`hari`,`mulai`,`selesai`,`mode`,`tautan`) VALUES ('12','12','2','5','13:00:00','14:40:00','Luring',NULL);
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('1','1','2','disetujui',NULL,'2026-10-07 13:38:03','2026-10-07 13:38:03');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('2','1','1','disetujui',NULL,'2026-10-07 13:38:04','2026-10-07 13:38:04');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('3','2','2','diajukan',NULL,'2026-10-07 13:38:04','2026-10-07 13:38:04');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('4','3','2','disetujui',NULL,'2026-10-07 13:38:05','2026-10-07 13:38:05');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('5','4','2','disetujui',NULL,'2026-10-07 13:38:05','2026-10-07 13:38:05');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('6','5','2','disetujui',NULL,'2026-10-07 13:38:06','2026-10-07 13:38:06');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('7','6','2','disetujui',NULL,'2026-10-07 13:38:06','2026-10-07 13:38:06');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('8','7','2','disetujui',NULL,'2026-10-07 13:38:07','2026-10-07 13:38:07');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('9','8','2','disetujui',NULL,'2026-10-07 13:38:08','2026-10-07 13:38:08');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('10','9','2','draf',NULL,'2026-10-07 13:38:08','2026-10-07 13:38:08');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('11','10','2','dikembalikan','Lengkapi pilihan mata kuliah sesuai rencana studi.','2026-10-07 13:38:09','2026-10-07 13:38:09');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('12','11','2','disetujui',NULL,'2026-10-07 13:38:34','2026-10-07 13:38:34');
INSERT INTO `krs` (`id`,`mahasiswa_id`,`periode_id`,`status`,`catatan`,`created_at`,`updated_at`) VALUES ('13','12','2','disetujui',NULL,'2026-10-07 14:40:43','2026-10-07 15:32:41');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('1','1','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('2','1','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('3','1','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('4','1','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('5','2','9');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('6','2','10');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('7','2','11');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('8','3','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('9','3','5');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('10','3','8');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('11','4','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('12','4','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('13','4','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('14','4','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('15','5','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('16','5','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('17','5','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('18','5','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('19','6','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('20','6','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('21','6','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('22','6','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('23','7','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('24','7','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('25','7','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('26','7','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('27','8','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('28','8','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('29','8','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('30','8','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('31','9','1');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('32','9','2');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('33','9','3');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('34','9','4');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('35','10','5');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('36','10','6');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('37','10','7');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('38','11','5');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('39','11','6');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('40','12','12');
INSERT INTO `krs_detail` (`id`,`krs_id`,`kelas_id`) VALUES ('42','13','8');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('1','1','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('2','1','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('3','1','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('4','1','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('5','2','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('6','2','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('7','2','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('8','2','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('9','3','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('10','3','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('11','3','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('12','3','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('13','4','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('14','4','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('15','4','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('16','4','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('17','5','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('18','5','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('19','5','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('20','5','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('21','6','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('22','6','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('23','6','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('24','6','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('25','7','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('26','7','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('27','7','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('28','7','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('29','8','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('30','8','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('31','8','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('32','8','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('33','9','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('34','9','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('35','9','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('36','9','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('37','10','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('38','10','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('39','10','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('40','10','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('41','11','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('42','11','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('43','11','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('44','11','UAS','40.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('45','12','Tugas','20.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('46','12','Kuis','10.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('47','12','UTS','30.00');
INSERT INTO `komponen_nilai` (`id`,`kelas_id`,`nama`,`bobot`) VALUES ('48','12','UAS','40.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('1','1','1','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('2','1','2','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('3','1','3','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('4','1','4','95.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('5','2','5','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('6','2','6','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('7','2','7','70.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('8','2','8','78.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('9','3','9','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('10','3','10','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('11','3','11','88.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('12','3','12','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('13','4','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('14','5','33','70.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('15','5','34','75.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('16','5','35','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('17','5','36','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('18','6','37','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('19','6','38','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('20','6','39','82.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('21','6','40','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('22','7','41','70.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('23','7','42','75.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('24','7','43','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('25','7','44','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('26','11','1','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('27','11','2','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('28','11','3','79.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('29','11','4','89.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('30','12','5','68.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('31','12','6','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('32','12','7','64.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('33','12','8','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('34','13','9','79.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('35','13','10','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('36','13','11','82.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('37','13','12','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('38','14','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('39','15','1','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('40','15','2','82.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('41','15','3','77.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('42','15','4','87.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('43','16','5','66.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('44','16','6','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('45','16','7','62.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('46','16','8','70.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('47','17','9','77.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('48','17','10','82.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('49','17','11','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('50','17','12','82.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('51','18','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('52','19','1','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('53','19','2','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('54','19','3','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('55','19','4','95.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('56','20','5','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('57','20','6','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('58','20','7','70.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('59','20','8','78.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('60','21','9','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('61','21','10','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('62','21','11','88.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('63','21','12','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('64','22','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('65','23','1','78.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('66','23','2','88.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('67','23','3','83.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('68','23','4','93.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('69','24','5','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('70','24','6','78.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('71','24','7','68.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('72','24','8','76.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('73','25','9','83.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('74','25','10','88.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('75','25','11','86.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('76','25','12','88.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('77','26','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('78','27','1','76.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('79','27','2','86.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('80','27','3','81.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('81','27','4','91.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('82','28','5','70.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('83','28','6','76.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('84','28','7','66.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('85','28','8','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('86','29','9','81.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('87','29','10','86.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('88','29','11','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('89','29','12','86.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('90','30','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('91','31','1','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('92','31','2','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('93','31','3','79.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('94','31','4','89.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('95','32','5','68.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('96','32','6','74.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('97','32','7','64.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('98','32','8','72.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('99','33','9','79.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('100','33','10','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('101','33','11','82.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('102','33','12','84.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('103','34','14','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('104','40','45','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('105','40','46','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('106','40','47','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('107','40','48','95.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('108','42','29','80.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('109','42','30','90.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('110','42','31','85.00');
INSERT INTO `nilai_komponen` (`id`,`krs_detail_id`,`komponen_nilai_id`,`nilai`) VALUES ('111','42','32','96.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('1','1','A','85.00','4.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('2','1','B+','80.00','3.50');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('3','1','B','70.00','3.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('4','1','C+','65.00','2.50');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('5','1','C','60.00','2.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('6','1','D','50.00','1.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('7','1','E','0.00','0.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('8','2','A','85.00','4.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('9','2','B+','80.00','3.50');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('10','2','B','70.00','3.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('11','2','C+','65.00','2.50');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('12','2','C','60.00','2.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('13','2','D','50.00','1.00');
INSERT INTO `skala_nilai` (`id`,`periode_id`,`huruf`,`minimum`,`angka`) VALUES ('14','2','E','0.00','0.00');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('1','1','1','2026-09-23','Konsep model relasional');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('2','1','2','2026-09-30','SQL dan integritas referensial');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('3','1','3','2026-10-07','Normalisasi basis data');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('4','4','1','2026-09-23','Struktur data dan tipe dasar');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('5','4','2','2026-09-30','Operasi array dan tabel');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('6','4','3','2026-10-07','Pengolahan dataset');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('7','12','1','2026-10-07','Perancangan tabel dan integritas referensial');
INSERT INTO `pertemuan` (`id`,`kelas_id`,`nomor`,`tanggal`,`topik`) VALUES ('8','8','1','2026-10-07','Relasi, normalisasi, dan pemeriksaan penerapan basis data');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('1','1','1','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('2','1','11','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('3','1','15','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('4','1','19','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('5','1','23','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('6','1','27','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('7','1','31','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('8','2','1','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('9','2','11','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('10','2','15','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('11','2','19','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('12','2','23','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('13','2','27','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('14','2','31','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('15','3','1','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('16','3','11','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('17','3','15','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('18','3','19','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('19','3','23','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('20','3','27','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('21','3','31','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('22','4','4','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('23','4','14','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('24','4','18','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('25','4','22','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('26','4','26','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('27','4','30','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('28','4','34','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('29','5','4','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('30','5','14','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('31','5','18','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('32','5','22','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('33','5','26','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('34','5','30','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('35','5','34','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('36','6','4','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('37','6','14','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('38','6','18','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('39','6','22','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('40','6','26','Izin');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('41','6','30','Sakit');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('42','6','34','Alpa');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('43','7','40','Hadir');
INSERT INTO `presensi` (`id`,`pertemuan_id`,`krs_detail_id`,`status`) VALUES ('44','8','42','Hadir');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('1','1','Siapkan data simulasi','sistem',NULL,'{\"periode_utama\": \"2026/2027 Ganjil\"}','2026-10-07 13:38:33');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('2','1','Siapkan contoh demonstrasi','sistem',NULL,'{\"kode\": \"PDB308\", \"sumber\": \"Seeder reproduksi hasil demonstrasi browser\"}','2026-10-07 13:38:35');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('3','13','Simpan draf KRS','krs','13','{\"kelas\": [8]}','2026-10-07 14:40:43');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('4','13','Ajukan KRS','krs','13','[]','2026-10-07 14:40:46');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('5','1','KRS dikembalikan','krs','13','{\"catatan\": \"Uji alur produksi: periksa kembali pilihan kelas sebelum mengajukan ulang.\"}','2026-10-07 15:02:54');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('6','13','Simpan draf KRS','krs','13','{\"kelas\": [8]}','2026-10-07 15:03:12');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('7','13','Ajukan KRS','krs','13','[]','2026-10-07 15:03:15');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('8','1','KRS disetujui','krs','13','{\"catatan\": null}','2026-10-07 15:32:41');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('9','16','Tambah pertemuan','pertemuan','8','{\"nomor\": \"1\", \"topik\": \"Relasi, normalisasi, dan pemeriksaan penerapan basis data\", \"tanggal\": \"2026-10-07\"}','2026-10-07 15:36:23');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('10','16','Simpan presensi','pertemuan','8','[]','2026-10-07 15:36:33');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('11','16','Simpan nilai','kelas','8','{\"peserta\": 1, \"perubahan\": [{\"sebelum\": null, \"sesudah\": \"0\", \"peserta_id\": 42, \"komponen_id\": 29}]}','2026-10-07 15:37:11');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('12','16','Simpan nilai','kelas','8','{\"peserta\": 1, \"perubahan\": [{\"sebelum\": \"0.00\", \"sesudah\": \"80\", \"peserta_id\": 42, \"komponen_id\": 29}, {\"sebelum\": null, \"sesudah\": \"90\", \"peserta_id\": 42, \"komponen_id\": 30}, {\"sebelum\": null, \"sesudah\": \"85\", \"peserta_id\": 42, \"komponen_id\": 31}, {\"sebelum\": null, \"sesudah\": \"95\", \"peserta_id\": 42, \"komponen_id\": 32}]}','2026-10-07 15:37:39');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('13','16','Terbitkan nilai','kelas','8','{\"alasan\": null}','2026-10-07 15:38:13');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('14','16','Buka koreksi nilai','kelas','8','{\"alasan\": \"Verifikasi ulang UAS pada data simulasi: nilai yang benar 96, sehingga hasil menjadi 88,90.\"}','2026-10-07 15:39:05');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('15','16','Simpan nilai','kelas','8','{\"peserta\": 1, \"perubahan\": [{\"sebelum\": \"95.00\", \"sesudah\": \"96\", \"peserta_id\": 42, \"komponen_id\": 32}]}','2026-10-07 15:39:42');
INSERT INTO `activity_log` (`id`,`user_id`,`aksi`,`entitas`,`record_id`,`detail`,`created_at`) VALUES ('16','16','Terbitkan nilai','kelas','8','{\"alasan\": null}','2026-10-07 15:39:55');
